oneup_uploader:
    mappings:
        avatar:
            frontend: dropzone
        logo:
            frontend: dropzone
        bninefile:
            frontend: dropzone
        media:
            frontend: dropzone
        gallery:
            frontend: dropzone
        file:
            frontend: dropzone